### ISSUE TITLE
Specifying workflow outputs

### ISSUE THREAD

**Issue by przemekiljan** [EliLillyCo/pytest-wdl#148]
Thanks for previous help, I was able to properly specify inputs and so tests are finally functional.  

I've encountered problems when trying to understand rules by which one can specify workflow outputs for later comparison with expected workflow. I also fail to find answers in provided documentation for your module.  

My workflow has many outputs that are not specified on workflow level. They are defined on task level instead. This here is my first question - is it possible to compare outputs from specific tasks instead of workflow ones?  

I figured that most possibly answer to previous question is "no", so solution for me would be to specify all outputs on workflow level. In that case I was met with another obstacle - how would one specify which workflow output to compare with file that contains expected values? I couldn't find exact instruction in docs, all I found was mention that one can create some sort of mapping that allows for more specific output comparison.

I'm sorry if those question don't fit regular issues purpose but I can't see any other mean of communication, in case the documentation isn't sufficient enough.

**Comment by michaeltneylon** [comment]
Hi @przemekiljan, glad you have made progress utilizing `pytest-wdl`!

Most of this is covered in the documentation but may be unclear because it is going to be specific to the execution engine you are using. Inputs are supplied and outputs are asserted for the same workflow or task that is declared in `workflow_runner`. [Whether a workflow or task can be run directly is executor specific.](https://pytest-wdl.readthedocs.io/en/stable/manual.html#executor-specific-workflow-runner-arguments) A workflow may contain many tasks, but assertion of outputs is only for the workflow or task run which is declared in `workflow_runner`.

In the case of testing specific tasks, you may want to write separate tests for those. If your executor does not allow running a task directly, you can write a test workflow WDL file in your tests directory that imports the task and calls it so you can run it and assert its outputs. This same approach of making "test workflows" can also be used if you want to run a whole workflow and check one of the task outputs but do not want your published WDL workflow
to map that same task output to workflow outputs. I will open a new issue on adding examples and motivation of this approach to the documentation.
